#!/bin/bash
# Terminal Setup Guide for FDP Session
# This helps you prepare your terminals before the demo

echo "=========================================="
echo "FDP Session Terminal Setup"
echo "=========================================="
echo ""
echo "Open 3 terminals and run these commands:"
echo ""
echo "=========================================="
echo "TERMINAL 1: MLflow UI"
echo "=========================================="
echo "cd /Users/lakkurra/mlops/MLFlow"
echo "source venv/bin/activate"
echo "mlflow ui"
echo ""
echo "Then open: http://localhost:5000"
echo ""
echo "=========================================="
echo "TERMINAL 2: Demo Commands"
echo "=========================================="
echo "cd /Users/lakkurra/mlops/MLFlow"
echo "source venv/bin/activate"
echo ""
echo "# Run when needed:"
echo "python demo_healthcare.py phi3:mini"
echo "python demo_drift_detection.py phi3:mini"
echo ""
echo "=========================================="
echo "TERMINAL 3: Drift Dashboard"
echo "=========================================="
echo "cd /Users/lakkurra/mlops/MLFlow"
echo "source venv/bin/activate"
echo "python drift_dashboard.py"
echo ""
echo "Then open: http://localhost:8051"
echo ""
echo "=========================================="
echo "Browser Tabs to Open:"
echo "=========================================="
echo "1. http://localhost:5000 (MLflow UI)"
echo "2. http://localhost:8051 (Drift Dashboard)"
echo ""
echo "=========================================="
echo "Pre-Demo Verification:"
echo "=========================================="
echo "python test_drift_detector.py"
echo "python test_mlflow_connection.py"
echo ""
echo "✅ Ready for demo!"
